name: Chatty
version: '${version}'
main: ru.brikster.chatty.Chatty
authors: [ Brikster ]

api-version: '26.2'

# Essentials needed only for overwriting existing private-messaging commands.
loadbefore: [ Essentials ]
softdepend: [ Vault, PlaceholderAPI ]

folia-supported: true
